services:
  - type: web
    name: ml-rag-backend
    env: python
    repo: https://github.com/AKholman/rag-langchain-ml-assistant.git
    branch: deployment
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
